/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-10-17 16:43:55 UTC)
 * on 2016-10-24 at 23:29:31 UTC 
 * Modify at your own risk.
 */

package com.example.com.example.entities.anxisendpoint.model;

/**
 * Model definition for Actividad.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the anxisendpoint. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Actividad extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String descripcion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_actividad")
  private java.lang.String idActividad;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> preguntasActividad;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String testAsociado;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String titulo;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescripcion() {
    return descripcion;
  }

  /**
   * @param descripcion descripcion or {@code null} for none
   */
  public Actividad setDescripcion(java.lang.String descripcion) {
    this.descripcion = descripcion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIdActividad() {
    return idActividad;
  }

  /**
   * @param idActividad idActividad or {@code null} for none
   */
  public Actividad setIdActividad(java.lang.String idActividad) {
    this.idActividad = idActividad;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getPreguntasActividad() {
    return preguntasActividad;
  }

  /**
   * @param preguntasActividad preguntasActividad or {@code null} for none
   */
  public Actividad setPreguntasActividad(java.util.List<java.lang.String> preguntasActividad) {
    this.preguntasActividad = preguntasActividad;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTestAsociado() {
    return testAsociado;
  }

  /**
   * @param testAsociado testAsociado or {@code null} for none
   */
  public Actividad setTestAsociado(java.lang.String testAsociado) {
    this.testAsociado = testAsociado;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTitulo() {
    return titulo;
  }

  /**
   * @param titulo titulo or {@code null} for none
   */
  public Actividad setTitulo(java.lang.String titulo) {
    this.titulo = titulo;
    return this;
  }

  @Override
  public Actividad set(String fieldName, Object value) {
    return (Actividad) super.set(fieldName, value);
  }

  @Override
  public Actividad clone() {
    return (Actividad) super.clone();
  }

}
