/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-10-17 16:43:55 UTC)
 * on 2016-10-24 at 23:29:31 UTC 
 * Modify at your own risk.
 */

package com.example.com.example.entities.anxisendpoint.model;

/**
 * Model definition for Encuesta.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the anxisendpoint. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Encuesta extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer ansiedad;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer confianza;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime fecha;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer general;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_encuesta")
  private java.lang.String idEncuesta;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer miedo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pacienteEncuesta;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer previsionMejora;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer sensacionFisica;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getAnsiedad() {
    return ansiedad;
  }

  /**
   * @param ansiedad ansiedad or {@code null} for none
   */
  public Encuesta setAnsiedad(java.lang.Integer ansiedad) {
    this.ansiedad = ansiedad;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getConfianza() {
    return confianza;
  }

  /**
   * @param confianza confianza or {@code null} for none
   */
  public Encuesta setConfianza(java.lang.Integer confianza) {
    this.confianza = confianza;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getFecha() {
    return fecha;
  }

  /**
   * @param fecha fecha or {@code null} for none
   */
  public Encuesta setFecha(com.google.api.client.util.DateTime fecha) {
    this.fecha = fecha;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getGeneral() {
    return general;
  }

  /**
   * @param general general or {@code null} for none
   */
  public Encuesta setGeneral(java.lang.Integer general) {
    this.general = general;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIdEncuesta() {
    return idEncuesta;
  }

  /**
   * @param idEncuesta idEncuesta or {@code null} for none
   */
  public Encuesta setIdEncuesta(java.lang.String idEncuesta) {
    this.idEncuesta = idEncuesta;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMiedo() {
    return miedo;
  }

  /**
   * @param miedo miedo or {@code null} for none
   */
  public Encuesta setMiedo(java.lang.Integer miedo) {
    this.miedo = miedo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPacienteEncuesta() {
    return pacienteEncuesta;
  }

  /**
   * @param pacienteEncuesta pacienteEncuesta or {@code null} for none
   */
  public Encuesta setPacienteEncuesta(java.lang.String pacienteEncuesta) {
    this.pacienteEncuesta = pacienteEncuesta;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPrevisionMejora() {
    return previsionMejora;
  }

  /**
   * @param previsionMejora previsionMejora or {@code null} for none
   */
  public Encuesta setPrevisionMejora(java.lang.Integer previsionMejora) {
    this.previsionMejora = previsionMejora;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getSensacionFisica() {
    return sensacionFisica;
  }

  /**
   * @param sensacionFisica sensacionFisica or {@code null} for none
   */
  public Encuesta setSensacionFisica(java.lang.Integer sensacionFisica) {
    this.sensacionFisica = sensacionFisica;
    return this;
  }

  @Override
  public Encuesta set(String fieldName, Object value) {
    return (Encuesta) super.set(fieldName, value);
  }

  @Override
  public Encuesta clone() {
    return (Encuesta) super.clone();
  }

}
