/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-10-17 16:43:55 UTC)
 * on 2016-10-24 at 23:29:31 UTC 
 * Modify at your own risk.
 */

package com.example.com.example.entities.anxisendpoint.model;

/**
 * Model definition for Paciente.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the anxisendpoint. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Paciente extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String apellidos;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String codigoPostal;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String direccion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> encuestas;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fobia;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_google")
  private java.lang.String idGoogle;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_paciente")
  private java.lang.String idPaciente;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String localidad;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String medicoAsociado;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> mensajes;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nick;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nombre;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String password;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String provincia;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String telefono;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> testAsociados;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer validado;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getApellidos() {
    return apellidos;
  }

  /**
   * @param apellidos apellidos or {@code null} for none
   */
  public Paciente setApellidos(java.lang.String apellidos) {
    this.apellidos = apellidos;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCodigoPostal() {
    return codigoPostal;
  }

  /**
   * @param codigoPostal codigoPostal or {@code null} for none
   */
  public Paciente setCodigoPostal(java.lang.String codigoPostal) {
    this.codigoPostal = codigoPostal;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDireccion() {
    return direccion;
  }

  /**
   * @param direccion direccion or {@code null} for none
   */
  public Paciente setDireccion(java.lang.String direccion) {
    this.direccion = direccion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public Paciente setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getEncuestas() {
    return encuestas;
  }

  /**
   * @param encuestas encuestas or {@code null} for none
   */
  public Paciente setEncuestas(java.util.List<java.lang.String> encuestas) {
    this.encuestas = encuestas;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFobia() {
    return fobia;
  }

  /**
   * @param fobia fobia or {@code null} for none
   */
  public Paciente setFobia(java.lang.String fobia) {
    this.fobia = fobia;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIdGoogle() {
    return idGoogle;
  }

  /**
   * @param idGoogle idGoogle or {@code null} for none
   */
  public Paciente setIdGoogle(java.lang.String idGoogle) {
    this.idGoogle = idGoogle;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIdPaciente() {
    return idPaciente;
  }

  /**
   * @param idPaciente idPaciente or {@code null} for none
   */
  public Paciente setIdPaciente(java.lang.String idPaciente) {
    this.idPaciente = idPaciente;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLocalidad() {
    return localidad;
  }

  /**
   * @param localidad localidad or {@code null} for none
   */
  public Paciente setLocalidad(java.lang.String localidad) {
    this.localidad = localidad;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMedicoAsociado() {
    return medicoAsociado;
  }

  /**
   * @param medicoAsociado medicoAsociado or {@code null} for none
   */
  public Paciente setMedicoAsociado(java.lang.String medicoAsociado) {
    this.medicoAsociado = medicoAsociado;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getMensajes() {
    return mensajes;
  }

  /**
   * @param mensajes mensajes or {@code null} for none
   */
  public Paciente setMensajes(java.util.List<java.lang.String> mensajes) {
    this.mensajes = mensajes;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNick() {
    return nick;
  }

  /**
   * @param nick nick or {@code null} for none
   */
  public Paciente setNick(java.lang.String nick) {
    this.nick = nick;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNombre() {
    return nombre;
  }

  /**
   * @param nombre nombre or {@code null} for none
   */
  public Paciente setNombre(java.lang.String nombre) {
    this.nombre = nombre;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPassword() {
    return password;
  }

  /**
   * @param password password or {@code null} for none
   */
  public Paciente setPassword(java.lang.String password) {
    this.password = password;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProvincia() {
    return provincia;
  }

  /**
   * @param provincia provincia or {@code null} for none
   */
  public Paciente setProvincia(java.lang.String provincia) {
    this.provincia = provincia;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTelefono() {
    return telefono;
  }

  /**
   * @param telefono telefono or {@code null} for none
   */
  public Paciente setTelefono(java.lang.String telefono) {
    this.telefono = telefono;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getTestAsociados() {
    return testAsociados;
  }

  /**
   * @param testAsociados testAsociados or {@code null} for none
   */
  public Paciente setTestAsociados(java.util.List<java.lang.String> testAsociados) {
    this.testAsociados = testAsociados;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getValidado() {
    return validado;
  }

  /**
   * @param validado validado or {@code null} for none
   */
  public Paciente setValidado(java.lang.Integer validado) {
    this.validado = validado;
    return this;
  }

  @Override
  public Paciente set(String fieldName, Object value) {
    return (Paciente) super.set(fieldName, value);
  }

  @Override
  public Paciente clone() {
    return (Paciente) super.clone();
  }

}
