/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-10-17 16:43:55 UTC)
 * on 2016-10-24 at 23:29:31 UTC 
 * Modify at your own risk.
 */

package com.example.com.example.entities.anxisendpoint.model;

/**
 * Model definition for Pregunta.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the anxisendpoint. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Pregunta extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String actividadAsociada;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_pregunta")
  private java.lang.String idPregunta;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("texto_pregunta")
  private java.lang.String textoPregunta;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getActividadAsociada() {
    return actividadAsociada;
  }

  /**
   * @param actividadAsociada actividadAsociada or {@code null} for none
   */
  public Pregunta setActividadAsociada(java.lang.String actividadAsociada) {
    this.actividadAsociada = actividadAsociada;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIdPregunta() {
    return idPregunta;
  }

  /**
   * @param idPregunta idPregunta or {@code null} for none
   */
  public Pregunta setIdPregunta(java.lang.String idPregunta) {
    this.idPregunta = idPregunta;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTextoPregunta() {
    return textoPregunta;
  }

  /**
   * @param textoPregunta textoPregunta or {@code null} for none
   */
  public Pregunta setTextoPregunta(java.lang.String textoPregunta) {
    this.textoPregunta = textoPregunta;
    return this;
  }

  @Override
  public Pregunta set(String fieldName, Object value) {
    return (Pregunta) super.set(fieldName, value);
  }

  @Override
  public Pregunta clone() {
    return (Pregunta) super.clone();
  }

}
