/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-10-17 16:43:55 UTC)
 * on 2016-10-24 at 23:29:31 UTC 
 * Modify at your own risk.
 */

package com.example.com.example.entities.anxisendpoint.model;

/**
 * Model definition for Test.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the anxisendpoint. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Test extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> actividadesTest;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String descripcion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime fechaFinalizacion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_test")
  private java.lang.String idTest;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String medicoCreador;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> pacientesAsociados;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String titulo;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getActividadesTest() {
    return actividadesTest;
  }

  /**
   * @param actividadesTest actividadesTest or {@code null} for none
   */
  public Test setActividadesTest(java.util.List<java.lang.String> actividadesTest) {
    this.actividadesTest = actividadesTest;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescripcion() {
    return descripcion;
  }

  /**
   * @param descripcion descripcion or {@code null} for none
   */
  public Test setDescripcion(java.lang.String descripcion) {
    this.descripcion = descripcion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getFechaFinalizacion() {
    return fechaFinalizacion;
  }

  /**
   * @param fechaFinalizacion fechaFinalizacion or {@code null} for none
   */
  public Test setFechaFinalizacion(com.google.api.client.util.DateTime fechaFinalizacion) {
    this.fechaFinalizacion = fechaFinalizacion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIdTest() {
    return idTest;
  }

  /**
   * @param idTest idTest or {@code null} for none
   */
  public Test setIdTest(java.lang.String idTest) {
    this.idTest = idTest;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMedicoCreador() {
    return medicoCreador;
  }

  /**
   * @param medicoCreador medicoCreador or {@code null} for none
   */
  public Test setMedicoCreador(java.lang.String medicoCreador) {
    this.medicoCreador = medicoCreador;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getPacientesAsociados() {
    return pacientesAsociados;
  }

  /**
   * @param pacientesAsociados pacientesAsociados or {@code null} for none
   */
  public Test setPacientesAsociados(java.util.List<java.lang.String> pacientesAsociados) {
    this.pacientesAsociados = pacientesAsociados;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTitulo() {
    return titulo;
  }

  /**
   * @param titulo titulo or {@code null} for none
   */
  public Test setTitulo(java.lang.String titulo) {
    this.titulo = titulo;
    return this;
  }

  @Override
  public Test set(String fieldName, Object value) {
    return (Test) super.set(fieldName, value);
  }

  @Override
  public Test clone() {
    return (Test) super.clone();
  }

}
